### ISSUE TITLE
Think about adding a pre-`commit!` step in `process-event`

### ISSUE THREAD

**Issue by zeitstein** [thheller/shadow-grove#7]
From [Slack](https://clojurians.slack.com/archives/C03NTBBSF46/p1667078218364709).

The idea is this would be similar to `tx-reporter`: a user-supplied function (similar signature to `tx-reporter`) and would default to no-op. It is a "user space" solution, but it gives the user the ability to 'hook' into the tx process and handle common tasks in a single place by leveraging the info from `commit!`. 

Silly **code example**:
```clojure
(let [db (-> {:x 1 :y 1}
               (db/transacted)
               ;; event handler
               (update :x inc))

        tx1 (db/commit! db)

        tx2 (-> (.-data db)
                (db/transacted)
                ;; you would do something based on tx1 here...
                (update :y inc)
                (db/commit!))]
    {:tx1 tx1 :tx2 tx2}
```

**Use cases**:
- attaching `:created/modified-at` to `keys-new/updated` from a single place, rather than in (many, complex) event handlers.
- 'automatic' backref management – for backref management, I resorted to writing a couple of functions to be used when touching the refs. But I often forget I need to use those functions. So, I thought about a general solution that would use info from commit! and run after each tx.
- handling undo/redo – I haven't thought a ton about undo/redo, but it seems again that it could be 'automated' by analyzing info from `commit!`. EDIT: I'm making this work by managing an undo `atom` from `tx-reporter`. So, the pre-commit! step is not necessary, but would still be preferable (over running a tx from tx-reporter) to have if one wished to store undo state inside grove db.
- A more concrete example ([from docs](https://github.com/thheller/shadow-grove/blob/master/doc/arch/database.md#query-considerations)):
  > Depending on the query complexity and frequency of affected updates it may be more efficient to store the result of that query in an actual :products-in-stock vector, and manually recomputing it whenever you change :stock. [also relevant to paragraphs above]

   So, "manually recomputing whenever you change :stock" can be difficult to enforce. You might change :stock in dozens of event handlers, or it might change as a result of server push. My 'proposal' would enable 'reacting' to :stock changing in a single place, without regard for how that change was made.
   (Of course, since granularity is at ident level, figuring out that :stock changed can be involved, but doable.)

**Comment by thheller** [comment]
I think at least half of these can be solved completely on the "user space" side of things, not internally. Yes, there should be more customizability, but that also opens the door to misusing things. Doing this incorrectly can potentially cripple the entire event subsystem performance. So, I'm keeping it lean until I figure something out.

> 'automatic' backref management

I have little interest in enabling this as part of after-the-fact commit handling. This is basically ["what the heck just happened?"](https://github.com/thheller/shadow-grove/blob/master/doc/what-the-heck-just-happened.md) all over again. Only keys are tracked. Checking every key, if something relevant actually happened is bad and better served by some APIs that actually to the right stuff when adding/changing back-refs directly.

> handling undo/redo

very similar. Undo/Redo likely shouldn't undo/redo the entire DB every time, only actual user actions should undo, not network effects that may have happened in the mean time. Again something likely better served in user space and not generic after commit.

> So, "manually recomputing whenever you change :stock" can be difficult to enforce. 

This is basically "materialized views". Non trivial and many possible solutions. Building it on top of a pre-commit hook doesn't seem ideal at all.

**Comment by zeitstein** [comment]
To be clear, opened the issue so this would not get 'lost'. I see your points – thanks for explaining! You can close the issue, if you wish.

**Comment by zeitstein** [comment]
> Undo/Redo likely shouldn't undo/redo the entire DB every time, only actual user actions should undo, not network effects that may have happened in the mean time.

To pushback slightly: I agree with this, but it can be managed simply with pre-commit! – check which event started the tx.

Thought of another use case for which I wish I had this: adding `modified-at` timestamps to `keys-updated`.

**Comment by thheller** [comment]
I'm still not totally sure about the API for this, but I added a basic "interceptor" design to the event handling. The idea being that you can run code before or after the actual event handler does its thing. They all get passed the `tx-env` and must return that, with modifications if necessary. In addition I added an accessor to get the current state of the running transaction, so that you can inspect the new/updated/removed keys.

So, the minimal example that does basically nothing is:

```
(sg/set-interceptors! rt-ref
 [{:before (fn [tx-env] tx-env)
   :after (fn [tx-env] tx-env)}])
```

`set-interceptors!` takes a pre-ordered vector of interceptors, since I didn't want to deal with having some kind of ad-hoc ordering mechanism. Each interceptor must have at least `:before` or `:after` fns, both is fine too.

In practice you'd probably want to move interceptor definition to some a `def`, e.g. `(def my-interceptor {:before ...})` and `(sg/set-interceptors! [some-ns/my-interceptor])`, otherwise the `set-interceptors!` call might get a bit unreadable.

The interceptors receive the regular `tx-env` just as any handler does. To get access to the transaction db state you can call `@(shadow.grove.db/tx-get (:db env))`, `tx-get` gives the actual Transaction object, deref gives you the current snapshot.

Since `tx-env` is passed through everything an interceptor can set some of its own state in `:before` and access it again in `:after` if needed.

This does not use the existing `tx-reporter`, as I want that to remain strictly for debugging.

As far as I can tell this covers all your mentioned use cases. Let me know if something is missing.

**Comment by zeitstein** [comment]
Finally got around to incorporating this – indeed covered all my use cases. Thanks!
